Repository Mak-API/website, pull requests merged in 2019-02, with the labels that each got.

#12 Feature/crud user
  assets/css/app.scss
  assets/css/components/class.scss
  assets/css/components/header.scss
  assets/css/components/profile.scss
  assets/css/components/signup.scss
  composer.json
  composer.lock
  config/bundles.php
  config/services.yaml
  public/images/png/Moi2_190118.png
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Traits/TimestampableTrait.php
  src/Entity/User.php
  src/EventListener/EntityListener.php
  src/EventListener/UserListener.php
  src/Form/UserType.php
  symfony.lock
  templates/components/header/homepage_header.html.twig
  templates/pagelayout.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  yarn.lock
Labels: enhancement

#21 Feature/crud user
  assets/css/components/signup.scss
  src/Controller/UserController.php
  src/Form/UserType.php
  templates/components/header/header.html.twig
  templates/components/header/homepage_header.html.twig
  templates/user/edit.html.twig
  templates/user/new.html.twig
Labels: enhancement

#26 Feature/impersonate user profiler
  composer.json
  composer.lock
  config/packages/security.yaml
  config/services.yaml
  src/DataCollector/RequestCollector.php
  templates/data_collector/template.html.twig
Labels: enhancement

#29 Feature/crud user
  .docker/php/php.ini
  config/packages/twig.yaml
  templates/form/form_theme.html.twig
  templates/user/edit.html.twig
Labels: enhancement

#51 Add opcache on our docker. Ready for test
  .docker/php/Dockerfile
  .docker/php/opcache.ini
Labels: bug

#45 Feature/edit name description
  assets/css/app.scss
  assets/css/components/class.scss
  assets/css/components/form-generator.scss
  assets/js/app.js
  assets/js/generator-form.js
  assets/js/generator/Generator.js
  assets/js/generator/head_form.js
  package.json
  templates/generator/_head_form.html.twig
  templates/generator/index_form.html.twig
  webpack.config.js
  yarn.lock
Labels: FRONT

#50 Add error page and add security access to routes
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/Front/SecurityController.php
  src/Controller/UserController.php
  src/Security/LoginFormAuthenticator.php
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/components/header/header.html.twig
  templates/security/login.html.twig
Labels: BACK, FRONT

#61 I increase routes security and I add redirection of authenticated users
  config/services.yaml
  src/Controller/Front/SecurityController.php
  src/Controller/UserController.php
  src/EventListener/RedirectUserListener.php
  src/Security/UserVoter.php
  templates/components/header/header.html.twig
  templates/user/show.html.twig
  translations/en_EN/validators.en.xlf
Labels: BACK, enhancement

#62 Hotfix/user create command
  src/Command/CreateUserCommand.php
Labels: BACK, enhancement

#55 Add some pages for exams
  assets/css/components/class.scss
  config/packages/twig_extensions.yaml
  src/Controller/Front/EditorialController.php
  symfony.lock
  templates/components/editorial_pages/about/about.html.twig
  templates/components/editorial_pages/editorial_page.html.twig
  templates/components/footer/footer.html.twig
  templates/components/header/header.html.twig
  templates/homepage/index.html.twig
Labels: BACK, FRONT, enhancement

#68 Hotfix/urgent
  src/Controller/Front/EditorialController.php
  src/Controller/RegistrationController.php
  src/EventListener/RedirectUserListener.php
  src/Service/EmailService.php
Labels: bug

#48 Adding a entity collapsible container
  assets/css/app.scss
  assets/css/components/class.scss
  assets/css/components/entity.scss
  assets/css/components/signup.scss
  templates/generator/_main_form.html.twig
  templates/user/edit.html.twig
Labels: FRONT

#71 Feature/delete profile
  README.md
  src/Controller/RegistrationController.php
  src/Controller/UserController.php
  src/Security/LoginFormAuthenticator.php
  src/Service/UserService.php
  templates/authentication/registration.html.twig
  templates/user/_delete_form.html.twig
  templates/user/delete.html.twig
  templates/user/show.html.twig
Labels: BACK, FRONT

#73 Feature/command delete user
  src/Command/CreateUserCommand.php
  src/Command/DeleteUserCommand.php
Labels: BACK

#76 Modify homepage description & init homepage.xlf
  templates/homepage/part_home.html.twig
  translations/en_EN/homepage.en.xlf
Labels: FRONT, enhancement

#78 add notification for successfull emailSending
  src/Controller/RegistrationController.php
  src/Service/UserService.php
  templates/authentication/registration.html.twig
Labels: BACK, FRONT

#80 Box create attribute & modification entity name
  assets/css/components/class.scss
  assets/css/components/entity.scss
  assets/js/generator/Generator.js
  templates/generator/_main_form.html.twig
Labels: FRONT, enhancement

#82 Generator API
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/routes/annotations.yaml
  src/Controller/Rest/ApiController.php
  src/Controller/Rest/ApiEntityController.php
  src/Controller/Rest/ApiEntityFieldController.php
  src/Controller/Rest/RestController.php
  src/Entity/ApiEntityRelation.php
  src/Entity/PaymentPlan.php
  src/Entity/Traits/TimestampableTrait.php
  src/Entity/User.php
  src/Exception/MismatchException.php
  src/Service/ApiEntityFieldService.php
  src/Service/ApiEntityRelationService.php
  src/Service/ApiEntityService.php
  src/Service/ApiService.php
  src/Service/PaymentPlanService.php
Labels: BACK, FRONT, GENERATOR

#83 Adding dynamical attribut in js
  assets/js/generator/Generator.js
  templates/generator/_main_form.html.twig
Labels: FRONT, enhancement

#79 add panel admin with dashboard + chartjs
  assets/css/app.scss
  assets/css/components/class.scss
  assets/css/components/dashboard-admin.scss
  assets/css/components/entity.scss
  assets/css/components/homepage.scss
  assets/css/components/signup.scss
  assets/css/variable/global.scss
  package.json
  shared_entry.js
  src/Controller/Back/AdminController.php
  src/Controller/Front/UserController.php
  templates/admin/index.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
  yarn.lock
Labels: BACK, FRONT

#85 delete attribute
  templates/generator/_main_form.html.twig
Labels: FRONT, enhancement

#86 Feature/add cron tasks
  README.md
  src/Command/ExecuteCommand.php
  src/Controller/Back/CronTasksController.php
  templates/back/crontasks/add.html.twig
  templates/back/crontasks/index.html.twig
Labels: enhancement

#92 Fixes ApiController methods
  src/Controller/Rest/ApiController.php
Labels: BACK

#93 Various fixes on API + services
  src/Controller/Rest/ApiController.php
  src/Controller/Rest/ApiEntityController.php
  src/Controller/Rest/ApiEntityFieldController.php
  src/Entity/Api.php
  src/Entity/Traits/DeletedTrait.php
  src/Service/ApiEntityFieldService.php
  src/Service/ApiEntityService.php
  src/Service/ApiService.php
Labels: BACK

#94 Change header wording
  templates/components/header/header.html.twig
  templates/components/header/homepage_header.html.twig
Labels: FRONT

#96 Remove creator
  src/Entity/Api.php
Labels: BACK

#97 first link form to create api
  templates/generator/_head_form.html.twig
  templates/generator/_main_form.html.twig
  templates/pagelayout.html.twig
Labels: FRONT

#100 Generator ⚡️
  .gitignore
  composer.json
  src/Controller/Rest/ApiEntityController.php
  src/Entity/Api.php
  src/Service/EmailService.php
  src/Service/Generator/AbstractFrameworkGenerator.php
  src/Service/Generator/Framework/SymfonyGenerator.php
  src/Utils/StringTools.php
  templates/services/generator/symfony/class.html.twig
  templates/services/generator/symfony/entity.html.twig
  templates/services/generator/symfony/repository.html.twig
Labels: BACK, GENERATOR

#101 Feature/add content website
  assets/css/components/_classParts/form.scss
  assets/css/components/class.scss
  assets/css/components/form-generator.scss
  assets/css/components/homepage.scss
  assets/css/components/profile.scss
  assets/css/components/signup.scss
  src/Controller/Generator/FormController.php
  src/Service/UserService.php
  templates/authentication/registration.html.twig
  templates/back/crontasks/index.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/components/editorial_pages/about/about.html.twig
  templates/components/header/header.html.twig
  templates/generator/index_form.html.twig
  templates/security/login.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: BACK, FRONT

#102 Hotfix
  src/Controller/Front/UserController.php
Labels: bug

#103 Zip and upload
  .gitignore
  composer.json
  composer.lock
  src/Controller/Rest/ApiController.php
  src/Entity/Api.php
  src/Service/ApiService.php
  src/Service/Generator/AbstractFrameworkGenerator.php
  src/Service/Generator/Framework/SymfonyGenerator.php
  templates/services/generator/symfony/entity.html.twig
Labels: BACK, GENERATOR

#99 edit attribute
  templates/generator/_main_form.html.twig
Labels: FRONT, enhancement

#104 adding apiId
  templates/generator/_main_form.html.twig
Labels: bug

#105 delete account template
  assets/css/app.scss
  assets/css/components/delete.scss
  templates/components/header/delete_header.html.twig
  templates/user/_delete_form.html.twig
Labels: FRONT, enhancement

#108 Feature/add content website
  assets/css/components/class.scss
  assets/css/components/dashboard-admin.scss
  assets/css/variable/global.scss
  public/images/favicons/favi.jpg
  src/Controller/Back/AdminController.php
  src/Controller/Back/NewsController.php
  src/Controller/Back/UserController.php
  src/Controller/Front/NewsController.php
  src/EventListener/UserListener.php
  src/Service/UserService.php
  templates/authentication/registration.html.twig
  templates/back/admin/index.html.twig
  templates/back/admin_base.html.twig
  templates/back/components/header/header.html.twig
  templates/back/components/panel.html.twig
  templates/back/crontasks/index.html.twig
  templates/back/news/index.html.twig
  templates/back/users/index.html.twig
  templates/components/editorial_pages/news/index.html.twig
  templates/components/editorial_pages/news/show.html.twig
  templates/components/header/header.html.twig
  templates/generator/_head_form.html.twig
  templates/pagelayout.html.twig
  templates/security/login.html.twig
  templates/user/_delete_form.html.twig
  templates/user/new.html.twig
Labels: BACK, FRONT, bug
